unstable_features = true
write_mode = "Diff"

comment_width = 79
normalize_comments = true
wrap_comments = true

condense_wildcard_suffixes = true

format_strings = true

imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true

match_block_trailing_comma = true

max_width = 79

report_fixme = "Always"
report_todo = "Always"

use_try_shorthand = true
